### ISSUE TITLE
backend error after last update

### ISSUE THREAD

**Issue by Phaeton** [mmcc-xx/BirdCAGE#27]
I am getting an error from the backend after the most recent update. Data never makes it over to `birdnetserver`.

``` 
[2023-06-06 15:15:59,810: ERROR/MainProcess] Task handler raised error: Task of kind 'app.stream_processing.record_stream' never registered, please make sure it's imported.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 649, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "/usr/local/lib/python3.10/site-packages/celery/app/registry.py", line 18, in __missing__
    raise self.NotRegistered(key)
celery.exceptions.NotRegistered: 'app.stream_processing.record_stream'
[2023-06-06 15:15:59,820: ERROR/MainProcess] Task handler raised error: Task of kind 'app.stream_processing.analyze_recordings' never registered, please make sure it's imported.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 649, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "/usr/local/lib/python3.10/site-packages/celery/app/registry.py", line 18, in __missing__
    raise self.NotRegistered(key)
celery.exceptions.NotRegistered: 'app.stream_processing.analyze_recordings'
```

**Comment by mmcc-xx** [comment]
Erg. I assume you tried taking the whole app down and restarting it? Maybe try pulling mmcc73/birdcage_backend:latest?

I have never seen an error like that - I'll do some poking around.

**Comment by mmcc-xx** [comment]
In order to make the tasks restart-able without shutting down the app, I'm now starting the function that starts and monitors the tasks in a separate thread. I wonder if that caused a weird race condition or some such thing.

**Comment by Phaeton** [comment]
> In order to make the tasks restart-able without shutting down the app, I'm now starting the function that starts and monitors the tasks in a separate thread.

So I need to increase concurrency or is that unrelated? 

> Erg. I assume you tried taking the whole app down and restarting it?

I tried lots of ups and downs to get it working. I ended up rolling back to an earlier version I still had.

**Comment by Phaeton** [comment]
It was concurrency. Increased that number and things started working again.

**Comment by mmcc-xx** [comment]
Weird. What did you set it to, and what was it before?

I think I do have a potential race condition by the way, even if that didn't cause your issue :)

**Comment by Phaeton** [comment]
So I had concurrency at 3 before, no issues. I had to increase it to 8 to get it to run. I put it back to default 10 to make sure it doesn't fail on cleanup in 24 hours. 

I will say it is inconsistent. It takes a couple restarts to make sure it actually starts working. I've seen it stall at a few different places now (even with higher concurrency).

**Comment by mmcc-xx** [comment]
I just pushed a new image with what I would guess is the problem addressed. Can you give that a try?

**Comment by mmcc-xx** [comment]
Also, by chance do you have more than one instance of redis running?

**Comment by Phaeton** [comment]
Only once instance of redis. Long error incoming....

```
[2023-06-06 19:55:50,360: WARNING/MainProcess] Exception in thread 
[2023-06-06 19:55:50,362: WARNING/MainProcess] Thread-2 (run_process_streams)
[2023-06-06 19:55:50,363: WARNING/MainProcess] :
[2023-06-06 19:55:50,364: WARNING/MainProcess] Traceback (most recent call last):
[2023-06-06 19:55:50,364: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/kombu/utils/functional.py", line 30, in __call__
[2023-06-06 19:55:50,370: WARNING/MainProcess]     
[2023-06-06 19:55:50,370: WARNING/MainProcess] return self.__value__
[2023-06-06 19:55:50,371: WARNING/MainProcess] AttributeError
[2023-06-06 19:55:50,371: WARNING/MainProcess] : 
[2023-06-06 19:55:50,372: WARNING/MainProcess] 'ChannelPromise' object has no attribute '__value__'
[2023-06-06 19:55:50,372: WARNING/MainProcess] . Did you mean: '
[2023-06-06 19:55:50,372: WARNING/MainProcess] __call__
[2023-06-06 19:55:50,373: WARNING/MainProcess] '?
[2023-06-06 19:55:50,373: WARNING/MainProcess] 
During handling of the above exception, another exception occurred:
[2023-06-06 19:55:50,373: WARNING/MainProcess] Traceback (most recent call last):
[2023-06-06 19:55:50,374: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/kombu/connection.py", line 446, in _reraise_as_library_errors
[2023-06-06 19:55:50,376: WARNING/MainProcess]     
[2023-06-06 19:55:50,376: WARNING/MainProcess] yield
[2023-06-06 19:55:50,377: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/kombu/connection.py", line 433, in _ensure_connection
[2023-06-06 19:55:50,378: WARNING/MainProcess]     
[2023-06-06 19:55:50,378: WARNING/MainProcess] return retry_over_time(
[2023-06-06 19:55:50,378: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/kombu/utils/functional.py", line 312, in retry_over_time
[2023-06-06 19:55:50,379: WARNING/MainProcess]     
[2023-06-06 19:55:50,379: WARNING/MainProcess] return fun(*args, **kwargs)
[2023-06-06 19:55:50,380: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/kombu/connection.py", line 877, in _connection_factory
[2023-06-06 19:55:50,381: WARNING/MainProcess]     
[2023-06-06 19:55:50,381: WARNING/MainProcess] self._connection = self._establish_connection()
[2023-06-06 19:55:50,381: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/kombu/connection.py", line 812, in _establish_connection
[2023-06-06 19:55:50,383: WARNING/MainProcess]     
[2023-06-06 19:55:50,383: WARNING/MainProcess] conn = self.transport.establish_connection()
[2023-06-06 19:55:50,383: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/kombu/transport/pyamqp.py", line 201, in establish_connection
[2023-06-06 19:55:50,385: WARNING/MainProcess]     
[2023-06-06 19:55:50,385: WARNING/MainProcess] conn.connect()
[2023-06-06 19:55:50,386: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/amqp/connection.py", line 323, in connect
[2023-06-06 19:55:50,388: WARNING/MainProcess]     
[2023-06-06 19:55:50,388: WARNING/MainProcess] self.transport.connect()
[2023-06-06 19:55:50,389: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/amqp/transport.py", line 129, in connect
[2023-06-06 19:55:50,392: WARNING/MainProcess]     
[2023-06-06 19:55:50,393: WARNING/MainProcess] self._connect(self.host, self.port, self.connect_timeout)
[2023-06-06 19:55:50,393: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/amqp/transport.py", line 184, in _connect
[2023-06-06 19:55:50,394: WARNING/MainProcess]     
[2023-06-06 19:55:50,394: WARNING/MainProcess] self.sock.connect(sa)
[2023-06-06 19:55:50,395: WARNING/MainProcess] ConnectionRefusedError
[2023-06-06 19:55:50,395: WARNING/MainProcess] : 
[2023-06-06 19:55:50,395: WARNING/MainProcess] [Errno 111] Connection refused
[2023-06-06 19:55:50,396: WARNING/MainProcess] 
The above exception was the direct cause of the following exception:
[2023-06-06 19:55:50,396: WARNING/MainProcess] Traceback (most recent call last):
[2023-06-06 19:55:50,396: WARNING/MainProcess]   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
[2023-06-06 19:55:50,402: WARNING/MainProcess]     
[2023-06-06 19:55:50,403: WARNING/MainProcess] self.run()
[2023-06-06 19:55:50,403: WARNING/MainProcess]   File "/usr/local/lib/python3.10/threading.py", line 953, in run
[2023-06-06 19:55:50,404: WARNING/MainProcess]     
[2023-06-06 19:55:50,405: WARNING/MainProcess] self._target(*self._args, **self._kwargs)
[2023-06-06 19:55:50,405: WARNING/MainProcess]   File "//celery_worker.py", line 18, in run_process_streams
[2023-06-06 19:55:50,405: WARNING/MainProcess]     
[2023-06-06 19:55:50,406: WARNING/MainProcess] process_streams(app)
[2023-06-06 19:55:50,406: WARNING/MainProcess]   File "/app/stream_processing.py", line 350, in process_streams
[2023-06-06 19:55:50,407: WARNING/MainProcess]     
[2023-06-06 19:55:50,407: WARNING/MainProcess] task_ids = start_tasks()
[2023-06-06 19:55:50,407: WARNING/MainProcess]   File "/app/stream_processing.py", line 334, in start_tasks
[2023-06-06 19:55:50,408: WARNING/MainProcess]     
[2023-06-06 19:55:50,408: WARNING/MainProcess] results = task_group.apply_async()
[2023-06-06 19:55:50,408: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/celery/canvas.py", line 1096, in apply_async
[2023-06-06 19:55:50,411: WARNING/MainProcess]     
[2023-06-06 19:55:50,411: WARNING/MainProcess] results = list(self._apply_tasks(tasks, producer, app, p,
[2023-06-06 19:55:50,412: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/celery/canvas.py", line 1203, in _apply_tasks
[2023-06-06 19:55:50,413: WARNING/MainProcess]     
[2023-06-06 19:55:50,414: WARNING/MainProcess] sig.apply_async(producer=producer, add_to_parent=False,
[2023-06-06 19:55:50,414: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/celery/canvas.py", line 219, in apply_async
[2023-06-06 19:55:50,414: WARNING/MainProcess]     
[2023-06-06 19:55:50,415: WARNING/MainProcess] return _apply(args, kwargs, **options)
[2023-06-06 19:55:50,415: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/celery/app/task.py", line 575, in apply_async
[2023-06-06 19:55:50,418: WARNING/MainProcess]     
[2023-06-06 19:55:50,419: WARNING/MainProcess] return app.send_task(
[2023-06-06 19:55:50,419: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/celery/app/base.py", line 788, in send_task
[2023-06-06 19:55:50,422: WARNING/MainProcess]     
[2023-06-06 19:55:50,423: WARNING/MainProcess] amqp.send_task_message(P, name, message, **options)
[2023-06-06 19:55:50,423: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/celery/app/amqp.py", line 510, in send_task_message
[2023-06-06 19:55:50,425: WARNING/MainProcess]     
[2023-06-06 19:55:50,426: WARNING/MainProcess] ret = producer.publish(
[2023-06-06 19:55:50,426: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/kombu/messaging.py", line 177, in publish
[2023-06-06 19:55:50,428: WARNING/MainProcess]     
[2023-06-06 19:55:50,429: WARNING/MainProcess] return _publish(
[2023-06-06 19:55:50,429: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/kombu/connection.py", line 523, in _ensured
[2023-06-06 19:55:50,430: WARNING/MainProcess]     
[2023-06-06 19:55:50,431: WARNING/MainProcess] return fun(*args, **kwargs)
[2023-06-06 19:55:50,432: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/kombu/messaging.py", line 186, in _publish
[2023-06-06 19:55:50,434: WARNING/MainProcess]     
[2023-06-06 19:55:50,434: WARNING/MainProcess] channel = self.channel
[2023-06-06 19:55:50,435: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/kombu/messaging.py", line 209, in _get_channel
[2023-06-06 19:55:50,435: WARNING/MainProcess]     
[2023-06-06 19:55:50,436: WARNING/MainProcess] channel = self._channel = channel()
[2023-06-06 19:55:50,436: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/kombu/utils/functional.py", line 32, in __call__
[2023-06-06 19:55:50,437: WARNING/MainProcess]     
[2023-06-06 19:55:50,437: WARNING/MainProcess] value = self.__value__ = self.__contract__()
[2023-06-06 19:55:50,437: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/kombu/messaging.py", line 225, in <lambda>
[2023-06-06 19:55:50,438: WARNING/MainProcess]     
[2023-06-06 19:55:50,438: WARNING/MainProcess] channel = ChannelPromise(lambda: connection.default_channel)
[2023-06-06 19:55:50,439: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/kombu/connection.py", line 895, in default_channel
[2023-06-06 19:55:50,440: WARNING/MainProcess]     
[2023-06-06 19:55:50,440: WARNING/MainProcess] self._ensure_connection(**conn_opts)
[2023-06-06 19:55:50,441: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/kombu/connection.py", line 432, in _ensure_connection
[2023-06-06 19:55:50,444: WARNING/MainProcess]     
[2023-06-06 19:55:50,445: WARNING/MainProcess] with ctx():
[2023-06-06 19:55:50,446: WARNING/MainProcess]   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
[2023-06-06 19:55:50,448: WARNING/MainProcess]     
[2023-06-06 19:55:50,448: WARNING/MainProcess] self.gen.throw(typ, value, traceback)
[2023-06-06 19:55:50,448: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/kombu/connection.py", line 450, in _reraise_as_library_errors
[2023-06-06 19:55:50,449: WARNING/MainProcess]     
[2023-06-06 19:55:50,449: WARNING/MainProcess] raise ConnectionError(str(exc)) from exc
[2023-06-06 19:55:50,449: WARNING/MainProcess] kombu.exceptions
[2023-06-06 19:55:50,451: WARNING/MainProcess] .
[2023-06-06 19:55:50,451: WARNING/MainProcess] OperationalError
[2023-06-06 19:55:50,453: WARNING/MainProcess] : 
[2023-06-06 19:55:50,453: WARNING/MainProcess] [Errno 111] Connection refused
```

**Comment by mmcc-xx** [comment]
I rolled back the changes that caused the issues. I think the current images should be back to the previous relative stability.

**Comment by Phaeton** [comment]
Seems to be running OK again on latest. I will close this out.
