### ISSUE TITLE
SQLite locked DB

### ISSUE THREAD

**Issue by rpatel3001** [mmcc-xx/BirdCAGE#29]
Sometimes on startup, a DB is locked, preventing the app from proceeding. Not the same table every time, and sometimes I get this multiple times in a row.

```
birdcage-birdcage_backend-1   | [2023-06-06 19:53:34,619: WARNING/MainProcess] Broker URL:
birdcage-birdcage_backend-1   | [2023-06-06 19:53:34,619: WARNING/MainProcess]  
birdcage-birdcage_backend-1   | [2023-06-06 19:53:34,619: WARNING/MainProcess] redis://redis:6379/0
birdcage-birdcage_backend-1   | [2023-06-06 19:53:34,620: WARNING/MainProcess] Result Backend URL:
birdcage-birdcage_backend-1   | [2023-06-06 19:53:34,620: WARNING/MainProcess]  
birdcage-birdcage_backend-1   | [2023-06-06 19:53:34,620: WARNING/MainProcess] redis://redis:6379/0
birdcage-birdcage_backend-1   | [2023-06-06 19:53:34,621: WARNING/MainProcess] Starting recording and analyze tasks
birdcage-birdcage_backend-1   | [2023-06-06 19:53:34,630: INFO/MainProcess] mingle: all alone
birdcage-birdcage_backend-1   | [2023-06-06 19:53:34,666: INFO/MainProcess] celery@b512e2e6bb55 ready.
birdcage-birdcage_backend-1   | [2023-06-06 19:53:34,694: INFO/MainProcess] Task app.stream_processing.record_stream[119a7d2f-3233-452b-936e-f81fafa6b8cf] received
birdcage-birdcage_backend-1   | [2023-06-06 19:53:34,699: WARNING/ForkPoolWorker-7] Starting record_stream for Shed
birdcage-birdcage_backend-1   | [2023-06-06 19:53:34,710: INFO/MainProcess] Task app.stream_processing.record_stream[083aee89-1c5b-43e4-a240-17ed38eae8db] received
birdcage-birdcage_backend-1   | [2023-06-06 19:53:34,716: INFO/MainProcess] Task app.stream_processing.analyze_recordings[13d2fd11-108e-4a3a-84c8-d513a44b2c13] received
birdcage-birdcage_backend-1   | [2023-06-06 19:53:34,718: WARNING/ForkPoolWorker-8] Starting record_stream for FrontYard
birdcage-birdcage_backend-1   | [2023-06-06 19:53:34,725: WARNING/ForkPoolWorker-1] Starting analyze_recordings
birdcage-birdcage_backend-1   | [2023-06-06 19:53:50,172: WARNING/ForkPoolWorker-7] Recording successful. File saved to: /app/../tmp/9428da7046774fc4b32755ce529631fe.wav
birdcage-birdcage_backend-1   | [2023-06-06 19:53:50,233: WARNING/ForkPoolWorker-8] Recording successful. File saved to: /app/../tmp/cb15f0ac04b7446dbdc8f5048fcd0ef0.wav
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,201: ERROR/ForkPoolWorker-7] Task app.stream_processing.record_stream[119a7d2f-3233-452b-936e-f81fafa6b8cf] raised unexpected: OperationalError('database is locked')
birdcage-birdcage_backend-1   | Traceback (most recent call last):
birdcage-birdcage_backend-1   |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
birdcage-birdcage_backend-1   |     R = retval = fun(*args, **kwargs)
birdcage-birdcage_backend-1   |   File "/app/__init__.py", line 84, in __call__
birdcage-birdcage_backend-1   |     return TaskBase.__call__(self, *args, **kwargs)
birdcage-birdcage_backend-1   |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
birdcage-birdcage_backend-1   |     return self.run(*args, **kwargs)
birdcage-birdcage_backend-1   |   File "/app/stream_processing.py", line 114, in record_stream
birdcage-birdcage_backend-1   |     set_metadata(os.path.basename(tmp_filename),
birdcage-birdcage_backend-1   |   File "/app/models/recording_metadata.py", line 59, in set_metadata
birdcage-birdcage_backend-1   |     connection.commit()
birdcage-birdcage_backend-1   | sqlite3.OperationalError: database is locked
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,750: WARNING/MainProcess] Exception in thread 
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,750: WARNING/MainProcess] Thread-2 (run_process_streams)
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,750: WARNING/MainProcess] :
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,750: WARNING/MainProcess] Traceback (most recent call last):
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,750: WARNING/MainProcess]   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,864: WARNING/MainProcess]     
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,864: WARNING/MainProcess] self.run()
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,865: WARNING/MainProcess]   File "/usr/local/lib/python3.10/threading.py", line 953, in run
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,866: WARNING/MainProcess]     
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,866: WARNING/MainProcess] self._target(*self._args, **self._kwargs)
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,867: WARNING/MainProcess]   File "//celery_worker.py", line 18, in run_process_streams
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,867: WARNING/MainProcess]     
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,867: WARNING/MainProcess] process_streams(app)
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,868: WARNING/MainProcess]   File "/app/stream_processing.py", line 353, in process_streams
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,868: WARNING/MainProcess]     
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,869: WARNING/MainProcess] if check_command_value('restart'):
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,869: WARNING/MainProcess]   File "/app/models/commands.py", line 35, in check_command_value
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,869: WARNING/MainProcess]     
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,870: WARNING/MainProcess] cursor.execute('SELECT value FROM commands WHERE name = ?', (command_name,))
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,870: WARNING/MainProcess] sqlite3
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,871: WARNING/MainProcess] .
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,871: WARNING/MainProcess] OperationalError
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,871: WARNING/MainProcess] : 
birdcage-birdcage_backend-1   | [2023-06-06 19:53:55,871: WARNING/MainProcess] database is locked
birdcage-birdcage_backend-1   | [2023-06-06 19:54:00,283: ERROR/ForkPoolWorker-1] Task app.stream_processing.analyze_recordings[13d2fd11-108e-4a3a-84c8-d513a44b2c13] raised unexpected: OperationalError('database is locked')
birdcage-birdcage_backend-1   | Traceback (most recent call last):
birdcage-birdcage_backend-1   |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
birdcage-birdcage_backend-1   |     R = retval = fun(*args, **kwargs)
birdcage-birdcage_backend-1   |   File "/app/__init__.py", line 84, in __call__
birdcage-birdcage_backend-1   |     return TaskBase.__call__(self, *args, **kwargs)
birdcage-birdcage_backend-1   |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
birdcage-birdcage_backend-1   |     return self.run(*args, **kwargs)
birdcage-birdcage_backend-1   |   File "/app/stream_processing.py", line 258, in analyze_recordings
birdcage-birdcage_backend-1   |     recording_metadata = get_metadata_by_filename(filename)
birdcage-birdcage_backend-1   |   File "/app/models/recording_metadata.py", line 24, in get_metadata_by_filename
birdcage-birdcage_backend-1   |     cursor.execute("SELECT * FROM recording_metadata WHERE filename = ?", (filename,))
birdcage-birdcage_backend-1   | sqlite3.OperationalError: database is locked
birdcage-birdcage_backend-1   | [2023-06-06 19:54:00,289: ERROR/ForkPoolWorker-8] Task app.stream_processing.record_stream[083aee89-1c5b-43e4-a240-17ed38eae8db] raised unexpected: OperationalError('database is locked')
birdcage-birdcage_backend-1   | Traceback (most recent call last):
birdcage-birdcage_backend-1   |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
birdcage-birdcage_backend-1   |     R = retval = fun(*args, **kwargs)
birdcage-birdcage_backend-1   |   File "/app/__init__.py", line 84, in __call__
birdcage-birdcage_backend-1   |     return TaskBase.__call__(self, *args, **kwargs)
birdcage-birdcage_backend-1   |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
birdcage-birdcage_backend-1   |     return self.run(*args, **kwargs)
birdcage-birdcage_backend-1   |   File "/app/stream_processing.py", line 114, in record_stream
birdcage-birdcage_backend-1   |     set_metadata(os.path.basename(tmp_filename),
birdcage-birdcage_backend-1   |   File "/app/models/recording_metadata.py", line 59, in set_metadata
birdcage-birdcage_backend-1   |     connection.commit()
birdcage-birdcage_backend-1   | sqlite3.OperationalError: database is locked
```

```
birdcage-birdcage_backend-1   | [2023-06-06 20:05:15,374: WARNING/MainProcess] Broker URL:
birdcage-birdcage_backend-1   | [2023-06-06 20:05:15,374: WARNING/MainProcess]  
birdcage-birdcage_backend-1   | [2023-06-06 20:05:15,374: WARNING/MainProcess] redis://redis:6379/0
birdcage-birdcage_backend-1   | [2023-06-06 20:05:15,374: WARNING/MainProcess] Result Backend URL:
birdcage-birdcage_backend-1   | [2023-06-06 20:05:15,375: WARNING/MainProcess]  
birdcage-birdcage_backend-1   | [2023-06-06 20:05:15,375: WARNING/MainProcess] redis://redis:6379/0
birdcage-birdcage_backend-1   | [2023-06-06 20:05:15,375: WARNING/MainProcess] Starting recording and analyze tasks
birdcage-birdcage_backend-1   | [2023-06-06 20:05:16,111: INFO/MainProcess] Connected to redis://redis:6379/0
birdcage-birdcage_backend-1   | [2023-06-06 20:05:16,119: INFO/MainProcess] mingle: searching for neighbors
birdcage-birdcage_backend-1   | [2023-06-06 20:05:17,128: INFO/MainProcess] mingle: all alone
birdcage-birdcage_backend-1   | [2023-06-06 20:05:17,157: INFO/MainProcess] celery@002fca5374d5 ready.
birdcage-birdcage_backend-1   | [2023-06-06 20:05:17,165: INFO/MainProcess] Task app.stream_processing.record_stream[48ff1b93-442a-4ffe-8a5b-3046a5d8137f] received
birdcage-birdcage_backend-1   | [2023-06-06 20:05:17,169: WARNING/ForkPoolWorker-7] Starting record_stream for Shed
birdcage-birdcage_backend-1   | [2023-06-06 20:05:17,172: INFO/MainProcess] Task app.stream_processing.record_stream[35cf2d6d-4595-4ff5-9f8f-759dedfe7421] received
birdcage-birdcage_backend-1   | [2023-06-06 20:05:17,177: INFO/MainProcess] Task app.stream_processing.analyze_recordings[b80a3354-514e-4b34-9ad3-29fa988b25f5] received
birdcage-birdcage_backend-1   | [2023-06-06 20:05:17,180: WARNING/ForkPoolWorker-8] Starting record_stream for FrontYard
birdcage-birdcage_backend-1   | [2023-06-06 20:05:17,181: WARNING/ForkPoolWorker-1] Starting analyze_recordings
birdcage-birdcage_backend-1   | [2023-06-06 20:05:22,221: ERROR/ForkPoolWorker-1] Task app.stream_processing.analyze_recordings[b80a3354-514e-4b34-9ad3-29fa988b25f5] raised unexpected: OperationalError('database is locked')
birdcage-birdcage_backend-1   | Traceback (most recent call last):
birdcage-birdcage_backend-1   |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
birdcage-birdcage_backend-1   |     R = retval = fun(*args, **kwargs)
birdcage-birdcage_backend-1   |   File "/app/__init__.py", line 84, in __call__
birdcage-birdcage_backend-1   |     return TaskBase.__call__(self, *args, **kwargs)
birdcage-birdcage_backend-1   |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
birdcage-birdcage_backend-1   |     return self.run(*args, **kwargs)
birdcage-birdcage_backend-1   |   File "/app/stream_processing.py", line 234, in analyze_recordings
birdcage-birdcage_backend-1   |     preferences = get_all_user_preferences(0)
birdcage-birdcage_backend-1   |   File "/app/models/preferences.py", line 67, in get_all_user_preferences
birdcage-birdcage_backend-1   |     cursor.execute('SELECT preference_key, preference_value FROM user_preferences WHERE user_id = ?',
birdcage-birdcage_backend-1   | sqlite3.OperationalError: database is locked
```

**Comment by Phaeton** [comment]
That looks familiar. I was getting that earlier as well.

**Comment by rpatel3001** [comment]
Interesting - I got the second error again (user_preferences) and it actually doesn't lock up the app, it just kills the analyze task. The recording task continues, and prints "Recording successful ...". Maybe this is related to #30? The first error did kill the recording and analyze tasks and didn't output anything else.

**Comment by mmcc-xx** [comment]
I think my new mechanism of starting up the app leaves something to be desired. I'll roll back those changes.

**Comment by mmcc-xx** [comment]
Changes have been rolled back. Please pull the new images and see if it works for you now.

**Comment by rpatel3001** [comment]
After a handful of restarts this hasn't happened again so I'll consider this closed. Thanks!

**Comment by mmcc-xx** [comment]
Thanks - I just implemented a different, and apparently more robust way of restarting the tasks.
