### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by rpatel3001** [mmcc-xx/BirdCAGE#30]
I'm having the same issue as #15 

After some hours of correct operation, recordings start piling up in the backend /tmp because nothing is being analyzed. My images are all up to date as of this minute. In normal operation, /tmp stays under 1 MB utilized. No error logs that I could see, I'll try to capture a copy next time and paste it here. I have 2 streams, concurrency set to 10. Restarting redis and birdnet doesn't help, a full stack restart does.

**Comment by mmcc-xx** [comment]
Definitely related - the analysis task was dying a terrible death while recording continued on. I rolled back the changes that caused the problem. Bad news is that you have to restart the app with any preference changes. Good news is that it doesn't break completely.

**Comment by rpatel3001** [comment]
To clarify, this issue with recordings not being analyzed happens after several hours of normal operation. The other issue was at startup. Is it possible that the other issue, that you fixed, is happening not at startup?

**Comment by mmcc-xx** [comment]
There is a task (managed with this thing call Celery that I admit I don't understand 100%) spun up for each stream for recording and another task for doing the analyzing. The recording tasks write wav files into the tmp directory. The analysis tasks reads these wav files in, sends them to the analysis engine, writes results to the database and saves off mp3s into the detections directory.

It sounds like the recording task(s) is/are working but the analysis task isn't. I think the analysis task died at startup.

Please try again if you don't mind with the latest images - you might need to explicitly do a `docker pull mmcc73/birdcage_backend:latest` and `docker pull mmcc73/birdcage_frontend:latest` to make sure you have the latest - to see if it now works. I screwed some stuff up trying to make it so those tasks could be restarted without stopping and starting the app completely.

**Comment by rpatel3001** [comment]
Will let you know how the latest images work, they are running OK since last night. But again, the problem happens after some hours of normal operation, without restarting the containers. The analyze thread dies several hours after startup.

**Comment by mmcc-xx** [comment]
Ok thank you! I misunderstood - I thought the analyze task was dying and then it took several hours for the tmp space to fill up.

**Comment by rpatel3001** [comment]
Just got this this morning:
```
birdcage-birdcage_backend-1  | [2023-06-08 06:11:23,025] ERROR in app: Exception on /api/detections/recent/5 [GET]
birdcage-birdcage_backend-1  | Traceback (most recent call last):
birdcage-birdcage_backend-1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
birdcage-birdcage_backend-1  |     response = self.full_dispatch_request()
birdcage-birdcage_backend-1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
birdcage-birdcage_backend-1  |     rv = self.handle_user_exception(e)
birdcage-birdcage_backend-1  |   File "/usr/local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
birdcage-birdcage_backend-1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
birdcage-birdcage_backend-1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
birdcage-birdcage_backend-1  |     rv = self.dispatch_request()
birdcage-birdcage_backend-1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
birdcage-birdcage_backend-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
birdcage-birdcage_backend-1  |   File "/app/views/detections.py", line 32, in get_recent_detections
birdcage-birdcage_backend-1  |     cursor.execute('SELECT * FROM detections ORDER BY timestamp DESC LIMIT ?', (limit,))
birdcage-birdcage_backend-1  | sqlite3.OperationalError: database is locked
birdcage-birdcage_backend-1  | [2023-06-08 06:11:23,069: ERROR/ForkPoolWorker-8] Task app.stream_processing.analyze_recordings[1c42523e-9f39-40db-b900-d7efffd78c98] raised unexpected: OperationalError('database is locked')
birdcage-birdcage_backend-1  | Traceback (most recent call last):
birdcage-birdcage_backend-1  |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
birdcage-birdcage_backend-1  |     R = retval = fun(*args, **kwargs)
birdcage-birdcage_backend-1  |   File "/app/__init__.py", line 84, in __call__
birdcage-birdcage_backend-1  |     return TaskBase.__call__(self, *args, **kwargs)
birdcage-birdcage_backend-1  |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
birdcage-birdcage_backend-1  |     return self.run(*args, **kwargs)
birdcage-birdcage_backend-1  |   File "/app/stream_processing.py", line 355, in analyze_recordings
birdcage-birdcage_backend-1  |     check_results(analysis['results'], file_path, recording_metadata, preferences, mqttclient)
birdcage-birdcage_backend-1  |   File "/app/stream_processing.py", line 202, in check_results
birdcage-birdcage_backend-1  |     detectionaction = getaction(scientific_name)
birdcage-birdcage_backend-1  |   File "/app/filter_functions.py", line 94, in getaction
birdcage-birdcage_backend-1  |     overrides = get_overrides_dict()
birdcage-birdcage_backend-1  |   File "/app/filter_functions.py", line 78, in get_overrides_dict
birdcage-birdcage_backend-1  |     overrides_jsonify = get_overrides(0)
birdcage-birdcage_backend-1  |   File "/app/views/filters.py", line 83, in get_overrides
birdcage-birdcage_backend-1  |     cursor.execute("SELECT species_name, override_type FROM species_overrides WHERE user_id = ?;", (user_id,))
birdcage-birdcage_backend-1  | sqlite3.OperationalError: database is locked
birdcage-birdcage_backend-1  | [2023-06-08 06:11:24,153: WARNING/ForkPoolWorker-1] Error in monitor_tasks:
birdcage-birdcage_backend-1  | [2023-06-08 06:11:24,154: WARNING/ForkPoolWorker-1]  
birdcage-birdcage_backend-1  | [2023-06-08 06:11:24,155: WARNING/ForkPoolWorker-1] database is locked
birdcage-birdcage_backend-1  | [2023-06-08 06:11:25,466: INFO/ForkPoolWorker-1] Task app.stream_processing.monitor_tasks[bb303746-3ff2-492f-b36e-817560b3ffbd] succeeded in 53845.885049953125s: None
birdcage-birdcage_backend-1  | [rtsp @ 0x5618d287a200] RTP: PT=60: bad cseq 1f6c expected=080b
```

This is after about 15 hours of properly analyzing recordings. After this recordings stopped being analyzed and filled up /tmp.

**Comment by mmcc-xx** [comment]
Huh - thanks for the log entries. I'll dig into locking behavior in sqlite databases - presumably the app is trying to read and write from the database at the same time and scenario isn't being handled.

**Comment by mmcc-xx** [comment]
Do you have any of the preceding log entries? Also, how many audio streams are you monitoring, what do you have your CONCURRENCY value set at in your docker-compose?

From what I have come to understand, only write operations cause the database to be locked, and when the read operations try to get a connection to the database there's a default 5 second timeout to wait for the lock to be released. I can't think of any write operations happening that would take longer than 5 seconds. It would be easy enough to increase the timeout, but it would be better to understand why any of the database operations would be taking so long.

Also, I should probably have better exception handling in the analysis task :)

**Comment by rpatel3001** [comment]
I restarted the container so no prior logs at the moment, I'll add them when it happens again. I have two streams, concurrency is set to 10.

**Comment by rpatel3001** [comment]
Just happened:

```
birdcage-birdcage_backend-1   | [2023-06-08 17:06:11,058: WARNING/ForkPoolWorker-7] Recording successful. File saved to: /app/../tmp/8bbb57f66c8b48639d73366a2012fe74.wav
birdcage-birdcage_backend-1   | [2023-06-08 17:06:11,945: WARNING/ForkPoolWorker-8] Requesting analysis for /app/../tmp/8bbb57f66c8b48639d73366a2012fe74.wav
birdcage-birdnetserver-1      | ####################  2023-06-08 17:06:11.958329  ####################
birdcage-birdnetserver-1      | {'lat': '40.6292536', 'lon': '-74.4193347', 'week': 23, 'overlap': '0', 'sensitivity': '1', 'sf_thresh': '0.03', 'pmode': 'max', 'num_results': 5, 'locale': 'en', 'save': False}
birdcage-birdnetserver-1      | Analyzing /tmp/tmp51w16phg.wav
birdcage-birdnetserver-1      | Finished /tmp/tmp51w16phg.wav in 3.25 seconds
birdcage-birdnetserver-1      | Results:
birdcage-birdnetserver-1      | {'6.0;9.0': [('Branta canadensis_Canada Goose', 0.0165), ('Meleagris gallopavo_Wild Turkey', 0.0044)], '12.0;15.0': [('Icterus spurius_Orchard Oriole', 0.0067), ('Icterus galbula_Baltimore Oriole', 0.0053), ('Pheucticus ludovicianus_Rose-breasted Grosbeak', 0.0051)]}
birdcage-birdcage_backend-1   | [2023-06-08 17:06:22,594: WARNING/ForkPoolWorker-6] Recording successful. File saved to: /app/../tmp/f0f9cc6f0c2d45f991179012fca3c9a0.wav
birdcage-birdcage_backend-1   | [2023-06-08 17:06:23,543: WARNING/ForkPoolWorker-8] Requesting analysis for /app/../tmp/f0f9cc6f0c2d45f991179012fca3c9a0.wav
birdcage-birdnetserver-1      | ####################  2023-06-08 17:06:23.551431  ####################
birdcage-birdnetserver-1      | {'lat': '40.6292536', 'lon': '-74.4193347', 'week': 23, 'overlap': '0', 'sensitivity': '1', 'sf_thresh': '0.03', 'pmode': 'max', 'num_results': 5, 'locale': 'en', 'save': False}
birdcage-birdnetserver-1      | Analyzing /tmp/tmpm8ik4jde.wav
birdcage-birdnetserver-1      | Finished /tmp/tmpm8ik4jde.wav in 1.69 seconds
birdcage-birdnetserver-1      | Results:
birdcage-birdnetserver-1      | {'12.0;15.0': [('Turdus migratorius_American Robin', 0.6303)], '3.0;6.0': [('Icterus galbula_Baltimore Oriole', 0.0371), ('Icterus spurius_Orchard Oriole', 0.0326), ('Mimus polyglottos_Northern Mockingbird', 0.0175), ('Spizella pusilla_Field Sparrow', 0.0128)]}
birdcage-birdcage_backend-1   | [2023-06-08 17:06:27,655: WARNING/ForkPoolWorker-7] Recording successful. File saved to: /app/../tmp/ba2da0feff464f6188487b1d93cef01b.wav
birdcage-birdcage_backend-1   | [2023-06-08 17:06:28,454: WARNING/ForkPoolWorker-8] Requesting analysis for /app/../tmp/ba2da0feff464f6188487b1d93cef01b.wav
birdcage-birdnetserver-1      | ####################  2023-06-08 17:06:28.466660  ####################
birdcage-birdnetserver-1      | {'lat': '40.6292536', 'lon': '-74.4193347', 'week': 23, 'overlap': '0', 'sensitivity': '1', 'sf_thresh': '0.03', 'pmode': 'max', 'num_results': 5, 'locale': 'en', 'save': False}
birdcage-birdnetserver-1      | Analyzing /tmp/tmpgsb1k7um.wav
birdcage-birdnetserver-1      | Finished /tmp/tmpgsb1k7um.wav in 2.16 seconds
birdcage-birdnetserver-1      | Results:
birdcage-birdnetserver-1      | {'0.0;3.0': [('Turdus migratorius_American Robin', 0.1727), ('Pheucticus ludovicianus_Rose-breasted Grosbeak', 0.0352)], '12.0;15.0': [('Icterus galbula_Baltimore Oriole', 0.0777), ('Icterus spurius_Orchard Oriole', 0.0227)], '6.0;9.0': [('Pandion haliaetus_Osprey', 0.0282)]}
birdcage-birdcage_backend-1   | [2023-06-08 17:06:39,566: WARNING/ForkPoolWorker-6] Recording successful. File saved to: /app/../tmp/43833efb289647768a792ca843ed284c.wav
birdcage-birdcage_backend-1   | [2023-06-08 17:06:41,212: WARNING/ForkPoolWorker-8] Requesting analysis for /app/../tmp/43833efb289647768a792ca843ed284c.wav
birdcage-birdnetserver-1      | ####################  2023-06-08 17:06:41.224903  ####################
birdcage-birdnetserver-1      | {'lat': '40.6292536', 'lon': '-74.4193347', 'week': 23, 'overlap': '0', 'sensitivity': '1', 'sf_thresh': '0.03', 'pmode': 'max', 'num_results': 5, 'locale': 'en', 'save': False}
birdcage-birdnetserver-1      | Analyzing /tmp/tmpuxj88hrx.wav
birdcage-birdnetserver-1      | Finished /tmp/tmpuxj88hrx.wav in 2.27 seconds
birdcage-birdnetserver-1      | Results:
birdcage-birdnetserver-1      | {'9.0;12.0': [('Turdus migratorius_American Robin', 0.7115)], '12.0;15.0': [('Catharus guttatus_Hermit Thrush', 0.0701)], '0.0;3.0': [('Icterus galbula_Baltimore Oriole', 0.0684), ('Icterus spurius_Orchard Oriole', 0.0518)], '3.0;6.0': [('Mimus polyglottos_Northern Mockingbird', 0.0345)]}
birdcage-birdcage_backend-1   | [2023-06-08 17:06:43,637: WARNING/ForkPoolWorker-8] Detected: American Robin Action: record
birdcage-birdcage_backend-1   | [2023-06-08 17:06:44,665: WARNING/ForkPoolWorker-7] Recording successful. File saved to: /app/../tmp/cd088960bfc44e3eaacc0e885ed732b7.wav
birdcage-birdcage_backend-1   | [2023-06-08 17:06:45,591: WARNING/ForkPoolWorker-8] Notifying
birdcage-birdcage_backend-1   | [2023-06-08 17:06:45,592: ERROR/ForkPoolWorker-8] There are no service(s) to notify
birdcage-birdcage_backend-1   | [2023-06-08 17:06:45,594: WARNING/ForkPoolWorker-8] MQTT not being used. Skipping publication.
birdcage-birdcage_backend-1   | [2023-06-08 17:06:49,288: WARNING/ForkPoolWorker-8] Requesting analysis for /app/../tmp/cd088960bfc44e3eaacc0e885ed732b7.wav
birdcage-birdnetserver-1      | ####################  2023-06-08 17:06:49.301003  ####################
birdcage-birdnetserver-1      | {'lat': '40.6292536', 'lon': '-74.4193347', 'week': 23, 'overlap': '0', 'sensitivity': '1', 'sf_thresh': '0.03', 'pmode': 'max', 'num_results': 5, 'locale': 'en', 'save': False}
birdcage-birdnetserver-1      | Analyzing /tmp/tmp_bphed_d.wav
birdcage-birdnetserver-1      | Finished /tmp/tmp_bphed_d.wav in 1.96 seconds
birdcage-birdnetserver-1      | Results:
birdcage-birdnetserver-1      | {'0.0;3.0': [('Pheucticus ludovicianus_Rose-breasted Grosbeak', 0.0207), ('Mimus polyglottos_Northern Mockingbird', 0.014), ('Melospiza melodia_Song Sparrow', 0.0096), ('Pandion haliaetus_Osprey', 0.0047)], '3.0;6.0': [('Turdus migratorius_American Robin', 0.0079)]}
birdcage-birdcage_backend-1   | [2023-06-08 17:06:57,847: WARNING/ForkPoolWorker-6] Recording successful. File saved to: /app/../tmp/77d848c0e1a643e3b7e22b27d3c798fc.wav
birdcage-birdcage_backend-1   | [2023-06-08 17:07:03,079: WARNING/ForkPoolWorker-1] Error in monitor_tasks:
birdcage-birdcage_backend-1   | [2023-06-08 17:07:03,080: WARNING/ForkPoolWorker-1]  
birdcage-birdcage_backend-1   | [2023-06-08 17:07:03,080: WARNING/ForkPoolWorker-1] database is locked
birdcage-birdcage_backend-1   | [2023-06-08 17:07:03,335: ERROR/ForkPoolWorker-8] Task app.stream_processing.analyze_recordings[44c8df42-daed-46e5-8197-63dc38b6cf31] raised unexpected: OperationalError('database is locked')
birdcage-birdcage_backend-1   | Traceback (most recent call last):
birdcage-birdcage_backend-1   |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
birdcage-birdcage_backend-1   |     R = retval = fun(*args, **kwargs)
birdcage-birdcage_backend-1   |   File "/app/__init__.py", line 84, in __call__
birdcage-birdcage_backend-1   |     return TaskBase.__call__(self, *args, **kwargs)
birdcage-birdcage_backend-1   |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
birdcage-birdcage_backend-1   |     return self.run(*args, **kwargs)
birdcage-birdcage_backend-1   |   File "/app/stream_processing.py", line 313, in analyze_recordings
birdcage-birdcage_backend-1   |     recording_metadata = get_metadata_by_filename(filename)
birdcage-birdcage_backend-1   |   File "/app/models/recording_metadata.py", line 24, in get_metadata_by_filename
birdcage-birdcage_backend-1   |     cursor.execute("SELECT * FROM recording_metadata WHERE filename = ?", (filename,))
birdcage-birdcage_backend-1   | sqlite3.OperationalError: database is locked
birdcage-birdcage_backend-1   | [2023-06-08 17:07:03,373: INFO/ForkPoolWorker-1] Task app.stream_processing.monitor_tasks[7bdea0dc-d7fc-478f-8bce-adf9c45ced28] succeeded in 30714.210146700032s: None
birdcage-birdcage_backend-1   | [2023-06-08 17:07:04,179: WARNING/ForkPoolWorker-7] Recording successful. File saved to: /app/../tmp/a6db46c4cadb47e6a428d546116eb1fa.wav
birdcage-birdcage_backend-1   | [2023-06-08 17:07:19,996: WARNING/ForkPoolWorker-6] Recording successful. File saved to: /app/../tmp/492fa4511e854b1fb59b5864bb3c7830.wav
birdcage-birdcage_backend-1   | [2023-06-08 17:07:23,612: WARNING/ForkPoolWorker-7] Recording successful. File saved to: /app/../tmp/c869a7517c0644fc8342e90ad4ed0fec.wav
birdcage-birdcage_backend-1   | [2023-06-08 17:07:37,188: WARNING/ForkPoolWorker-6] Recording successful. File saved to: /app/../tmp/a0086d1b4dc74e1680a72210d7294f6a.wav
birdcage-birdcage_backend-1   | [2023-06-08 17:07:40,806: WARNING/ForkPoolWorker-7] Recording successful. File saved to: /app/../tmp/e992b28e79c64bb185d0cf4c77d9e5ed.wav
birdcage-birdcage_backend-1   | [2023-06-08 17:07:54,204: WARNING/ForkPoolWorker-6] Recording successful. File saved to: /app/../tmp/c8bf4cd61164430896800d495ab9c725.wav
birdcage-birdcage_backend-1   | [2023-06-08 17:07:58,361: WARNING/ForkPoolWorker-7] Recording successful. File saved to: /app/../tmp/d49bd995e935491c865b6dbbfe92c265.wav
birdcage-birdcage_backend-1   | [2023-06-08 17:08:11,210: WARNING/ForkPoolWorker-6] Recording successful. File saved to: /app/../tmp/3f195e89587a41c389f7823e910f2e65.wav
```
Continues like that until /tmp fills up, then:
```
birdcage-birdcage_backend-1   | [2023-06-08 17:16:22,156: WARNING/ForkPoolWorker-7] Recording successful. File saved to: /app/../tmp/1e6086f6e90e43b197da0e0abe84ad8e.wav
birdcage-birdcage_backend-1   | [2023-06-08 17:16:35,377: WARNING/ForkPoolWorker-6] Recording successful. File saved to: /app/../tmp/063e87cd281245a4ad8fea7530e444ae.wav
birdcage-birdcage_backend-1   | Error writing trailer of /app/../tmp/2588220a7cf543539d335a738d0017b3.wav: No space left on device
birdcage-birdcage_backend-1   | [2023-06-08 17:16:38,885: WARNING/ForkPoolWorker-7] Recording successful. File saved to: /app/../tmp/2588220a7cf543539d335a738d0017b3.wav
birdcage-birdcage_backend-1   | [wav @ 0x55c3e2ba3fc0] Non-monotonous DTS in output stream 0:0; previous: 12624, current: 12608; changing to 12624. This may result in incorrect timestamps in the output file.
birdcage-birdcage_backend-1   | Error writing trailer of /app/../tmp/7ee2490d86c0428fbab2eb8b3ecc7edd.wav: No space left on device
birdcage-birdcage_backend-1   | [2023-06-08 17:16:52,374: WARNING/ForkPoolWorker-6] Recording successful. File saved to: /app/../tmp/7ee2490d86c0428fbab2eb8b3ecc7edd.wav
birdcage-birdcage_backend-1   | Error writing trailer of /app/../tmp/a275b88b5ca94a6d90ff40b00a218558.wav: No space left on device
birdcage-birdcage_backend-1   | [2023-06-08 17:16:55,482: WARNING/ForkPoolWorker-7] Recording successful. File saved to: /app/../tmp/a275b88b5ca94a6d90ff40b00a218558.wav
birdcage-birdcage_backend-1   | Error writing trailer of /app/../tmp/31a751c5384642fea09c4c01ef0027ed.wav: No space left on device
birdcage-birdcage_backend-1   | [2023-06-08 17:17:08,913: WARNING/ForkPoolWorker-6] Recording successful. File saved to: /app/../tmp/31a751c5384642fea09c4c01ef0027ed.wav
birdcage-birdcage_backend-1   | Error writing trailer of /app/../tmp/87fbf6778ecf45cc87a4b248eed3b593.wav: No space left on device
birdcage-birdcage_backend-1   | [2023-06-08 17:17:13,242: WARNING/ForkPoolWorker-7] Recording successful. File saved to: /app/../tmp/87fbf6778ecf45cc87a4b248eed3b593.wav
birdcage-birdcage_backend-1   | Error writing trailer of /app/../tmp/95c17af623014ef8a06c7d35ef759e49.wav: No space left on device
birdcage-birdcage_backend-1   | [2023-06-08 17:17:25,408: WARNING/ForkPoolWorker-6] Recording successful. File saved to: /app/../tmp/95c17af623014ef8a06c7d35ef759e49.wav
```

**Comment by mmcc-xx** [comment]
Thanks I was just looking into this.

Apropos of nothing, I had a male rose breasted grosbeak at my feeder today. What a lovely bird.

**Comment by mmcc-xx** [comment]
How long are your recordings? Analyzing takes 1.7 to 3.25 seconds which is significantly longer that I'm seeing. 

Anyway, I'm going

**Comment by mmcc-xx** [comment]
OK - try mmcc73/birdage_backend_rajan:latest in place of mmcc73/birdage_backend:latest and let me know what happens.

**Comment by rpatel3001** [comment]
Will do, thank you.

Recordings are set to 15 seconds. This is running in a VM on Proxmox. I'll try increasing the cores allocated and see if the processing times come down.

**Comment by rpatel3001** [comment]
Increasing from 2 to 4 cores didn't seem to help much if at all. Not sure if the library used benefits from more cores or is bound by single core performance. I'm running on an old server with 2x Xeon X5570.

**Comment by mmcc-xx** [comment]
Now that you mention it… I think there’s a way to get the analysis component to use multiple threads - I’ll have to check.

**Comment by rpatel3001** [comment]
so far so good, it's never run this long without failure before

**Comment by mmcc-xx** [comment]
Good to hear. I'll be pushing an update soon with better exception handling as well as some app health information in the UI

**Comment by mmcc-xx** [comment]
I just pushed that update and it has the extended timeout and everything that was in the image I asked you to use as well.

**Comment by rpatel3001** [comment]
gonna close this, seems stable. Thanks!
